---
name: "notify_slack_execution_change"
pack: "st2"
description: "Watches for an execution status of "awaits" for a certain action ref
enabled: true

trigger:
  type: core.st2.generic.actiontrigger

criteria:
  trigger.action_ref:
      type: equals
      pattern : st2.ask
  trigger.status:
      type: equals
      pattern : awaits

action:
  ref: slack.post_message
  parameters:
    message: '{{trigger.execution_id}} is awaiting an approval action'
